package org.collexio.persistence;

import org.collexio.business.domain.Item;

import java.sql.SQLException;
import java.util.List;
import java.util.Optional;

public interface ItemDAO {
    void add(Item item, Long collectionId) throws SQLException; // the item id is autogenerated, the id of the objct is ignored
    Optional<Item> get(Long id) throws SQLException;
    List<Item> getByCollectionId(Long collectionId) throws SQLException;
    void update(Item item, boolean noCollection) throws SQLException; // noCollection = true -> remove the item from the collection
    void delete(Long id) throws SQLException;
    List<Item> getAll() throws SQLException;
}
