package org.collexio.persistence;

import org.collexio.domain.Item;
import org.collexio.domain.ItemPhoto;

import java.sql.SQLException;
import java.util.List;
import java.util.Optional;

public interface ItemPhotoDAO {
    void add(ItemPhoto photo, Long itemId) throws SQLException; //the photo id is autogenerated, the id of the object is ignored
    Optional<ItemPhoto> get(Long id) throws SQLException;
    Optional<ItemPhoto> getByItemId(Long itemId) throws SQLException;
    void update(ItemPhoto photo) throws SQLException;
    //void delete(String id);
    List<ItemPhoto> getAll() throws SQLException;
    Optional<ItemPhoto> getLast() throws SQLException;
}
