package org.collexio.persistence;

import org.collexio.domain.Item;
import org.collexio.domain.Transaction;

import java.sql.SQLException;
import java.util.List;
import java.util.Optional;
import java.util.Set;

public interface TransactionDAO {
    void add(Transaction transaction, Long itemId) throws SQLException; //the transaction id is autogenerated, the id of the object is ignored
    Optional<Transaction> get(Long id) throws SQLException;
    void update(Transaction transaction, boolean noItem) throws SQLException;
    void delete(Long id) throws SQLException;
    Set<Transaction> getAll() throws SQLException;
    Set<Transaction> getByItemId(Long itemId) throws SQLException;
}
