package org.collexio.persistence.dao;


import org.collexio.persistence.entity.ItemPhotoEntity;

import java.sql.SQLException;
import java.util.List;
import java.util.Optional;

public interface ItemPhotoDAO {
    ItemPhotoEntity add(ItemPhotoEntity photo, Long itemId) throws SQLException; //the photo id is autogenerated, the id of the object is ignored
    Optional<ItemPhotoEntity> get(Long id) throws SQLException;
    Optional<ItemPhotoEntity> getByItemId(Long itemId) throws SQLException;
    void update(ItemPhotoEntity photo) throws SQLException;
    List<ItemPhotoEntity> getAll() throws SQLException;
    void deleteByItemId(Long id)throws SQLException;
}
