package org.collexio.persistence.dao;

import org.collexio.persistence.model.ItemEntity;
import org.collexio.persistence.model.ItemSpecEntity;

import java.sql.SQLException;
import java.util.List;
import java.util.Optional;

public interface ItemDAO {
    // before the add, insert the collection and the specs
    ItemEntity add(ItemEntity item, Long collectionId) throws SQLException; // the item id is autogenerated, the id of the objct is ignored
    Optional<ItemEntity> get(Long id) throws SQLException;
    List<ItemEntity> getByCollectionId(Long collectionId) throws SQLException;
    void update(ItemEntity item, Long collectionId) throws SQLException; // noCollection = true -> remove the item from the collection
    void delete(Long id) throws SQLException;
    List<ItemEntity> getAll() throws SQLException;
    Optional<Long> getCollectionId(Long id) throws SQLException;

}
