package org.collexio.persistence.dao;

import org.collexio.persistence.model.TransactionEntity;
import java.sql.SQLException;
import java.util.List;
import java.util.Optional;

public interface TransactionDAO {
    TransactionEntity add(TransactionEntity transaction, Long itemId) throws SQLException; //the transaction id is autogenerated, the id of the object is ignored
    Optional<TransactionEntity> get(Long id) throws SQLException;
    void update(TransactionEntity transaction) throws SQLException;
    void delete(Long id) throws SQLException;
    List<TransactionEntity> getAll() throws SQLException;
    List<TransactionEntity> getByItemId(Long itemId) throws SQLException;
    Long getItemId(Long id) throws SQLException;
}
